// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZXBIoUmP6kWF0rDoT13EI0FaAqh_nGdw',
    appId: '1:366914936426:android:7d2393ccb8b3bdda1a3413',
    messagingSenderId: '366914936426',
    projectId: 'seeds-77371',
    databaseURL: 'https://seeds-77371.firebaseio.com',
    storageBucket: 'seeds-77371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7WOc4uKnUqlvCilb9Zt9IkBU9ib_Tn8',
    appId: '1:366914936426:ios:75e7ba91678551811a3413',
    messagingSenderId: '366914936426',
    projectId: 'seeds-77371',
    databaseURL: 'https://seeds-77371.firebaseio.com',
    storageBucket: 'seeds-77371.appspot.com',
    androidClientId: '366914936426-kn6vumn468dl6vc1rdp9ircp6v9ehufg.apps.googleusercontent.com',
    iosClientId: '366914936426-eop45t8oepqu48v4fsp8frgqo0h0fmqd.apps.googleusercontent.com',
    iosBundleId: 'com.joinseeds.seedslight',
  );
}
